- name: Create a sandbox instance
  hosts: localhost
  remote_user: ubuntu #El usuario para conectarse por ssh, por default es ec2-user
  vars:
    keypair: con_pem #Nombre de los Key pair
    instance_type: t2.micro
    security_group: launch-wizard-1
    image: ami-0ac019f4fcb7cb7e6
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         count: 2 #Número de instancias a crear
      register: ec2

    - name: Add new instance to host group
      add_host: #Modulo para agrupar host
        hostname: "{{ item.public_ip }}"
        groupname: launched # nombre de grupo de instancias creadas
      with_items: "{{ ec2.instances }}"

#Install python & httpd
- hosts: launched #nombre de grupo de instancias
  become: true
  connection: ssh
  remote_user: ubuntu
  gather_facts: false
  pre_tasks:
    - name: 'install python'
      raw: 'sudo yum -y install python'
  tasks:
  #  Instala Docker
    - name: Instala Docker
      yum:
        name: docker-ce
        state: started



  tasks:
    - name: Instala NGINX
      apt:
        name: nginx
        state: present
    #  Instala Docker
    - name: Instala Docker
      apt:
        name: docker-ce
        state: present
